# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='taxonomy',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
