# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_taxonomy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('order_id', '-created_at')},
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='file',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
