# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('file', '0004_auto_20171004_0934'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='file',
            index_together=set([('content_type', 'object_id', 'order_id')]),
        ),
    ]
