# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20171004_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
