# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:42
from __future__ import unicode_literals

import cotidia.file.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_file_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f',
            field=cotidia.file.fields.CustomFileField(upload_to='uploads/'),
        ),
    ]
