# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_auto_20171025_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='file',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
