# Generated by Django 2.0.2 on 2018-07-06 13:19

import cotidia.file.fields
import cotidia.file.utils.filename
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20180201_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f',
            field=cotidia.file.fields.CustomFileField(upload_to=cotidia.file.utils.filename.get_file_path),
        ),
    ]
