# Generated by Django 2.0.2 on 2018-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_auto_20180706_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='alt_tags',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
