# Generated by Django 2.0.2 on 2019-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_auto_20180718_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='alt_tags',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
